### ISSUE TITLE
Unlock swfchan.com

### ISSUE THREAD

**Issue by indrakaw** [gvoze32/blockhostid#39]
Ada dua versi Swfchan:
1. `swfchan.com` (origin, beberapa nsfw)
2. `swfchan.net` (safe search, semua item diarahkan ke swfchan.com)

.net itu aman, yang .com itu bermasalah. 

Unlock, please?

**Comment by gvoze32** [comment]
Done.

**Comment by indrakaw** [comment]
Alright. :smile::ok_hand:
