### ISSUE TITLE
Tumblr.com

### ISSUE THREAD

**Issue by indrakaw** [gvoze32/blockhostid#41]
Beberapa blog dari tumblr.com kena internet positif. Blog yang diblokir adalah subdomain tumblr spesifik. Please fix.

**Comment by gvoze32** [comment]
Untuk domain spesifik, saya tidak bisa unblock semuanya, harus satu-satu cara ngelistnya, nah itu yang susah. Saya juga belum nemu solusinya, tapi sepertinya memang tidak bisa, harus satu-satu. Jika tetep ingin unblock, silahkan kirim list subdomainnya, nanti saya list.
